#HTTP Server
server:
  port: ${PORT:7010}

#Discovery Server Access
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default-zone: http://localhost:8761/eureka/
  instance : 
    hostname : localhost
    status-page-url-path: /infoBenefits
    health-check-url-path: /healthBenefits
    metadata-map:
       app-owner: Haku Corp
       description: Microservice for Benefits management
       
management:
  endpoint:
    restart:
      enabled: true
    health: 
      enabled: true
    info:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
    
       
spring:
  data:
    mongodb:
      uri: mongodb://hakuUser:hakuPass@localhost:27017/haku_db
      database: haku_db
      port: 27017
      host: localhost
      username: hakuUser
      password: hakuPass
  cloud:
    discovery:
      client:
        health-indicator:
          enabled: true
