#HTTP Server
server:
  port: ${PORT:7060}

#Discovery Server Access
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance : 
    hostname : localhost
    preferIpAddress: true
    #ipAddress: localhost
    status-page-url-path: /infoRedeemed
    health-check-url-path: /healthRedeemed
    metadata-map:
       app-owner: Haku  
       description: Microservice for Redeemed management

management:
  endpoints:
    web:
      exposure:
        include: '*'

spring:
  data:
    mongodb:
      uri: mongodb://hakuUser:hakuPass@localhost:27017/haku_db
      database: haku_db
      port: 27017
      host: localhost
      username: hakuUser
      password: hakuPass
      
security:
  oauth2:
    resource:
      user-info-uri: http://localhost:5100/auth/auth/user
