#HTTP Server
server:
  port: ${PORT:7000}

#Discovery Server Access
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance : 
    hostname : localhost
    status-page-url-path: /infoCategories
    health-check-url-path: /healthCategories
    metadata-map:
       app-owner: Haku  
       description: Microservice for Categories management

management:
  endpoint:
    restart:
      enabled: true
    health: 
      enabled: true
    info:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'

spring:
  data:
    mongodb:
      uri: mongodb://hakuUser:hakuPass@localhost:27017/haku_db
      database: haku_db
      port: 27017
      host: localhost
      username: hakuUser
      password: hakuPass
  cloud:
    discovery:
      client:
        health-indicator:
          enabled: true

security:
  oauth2:
    resource:
      user-info-uri: http://localhost:5100/auth/auth/user
