#HTTP Server
server:
  port: ${PORT:7000}

#Discovery Server Access
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    status-page-url-path: /infoCategories
    health-check-url-path: /healthCategories
    metadata-map:
       app-owner: Haku  
       description: Microservice for Categories management

spring:
  data:
    mongodb:
      uri: mongodb://hakuUser:hakuPass@localhost:27017/haku_db
      database: haku_db
      port: 27017
      host: localhost
      username: hakuUser
      password: hakuPass
