#HTTP Server
server:
  port: ${PORT:7050}

#Discovery Server Access
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance : 
    hostname : localhost
    status-page-url-path: /infoBusiness
    health-check-url-path: /healthBusiness
    metadata-map:
       app-owner: Haku  
       description: Microservice for Business management
       
spring:
  data:
    mongodb:
      uri: mongodb://hakuUser:hakuPass@localhost:27017/haku_db
      database: haku_db
      port: 27017
      host: localhost
      username: hakuUser
      password: hakuPass
