#HTTP Server
server:
  port: 7040

#Discovery Server Access
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance : 
    hostname : localhost
    status-page-url-path: /infoBranches
    health-check-url-path: /healthBranches
    metadata-map:
       app-owner: Haku  
       description: Microservice for Branches management
       
spring:
  management:
  endpoint:
    restart:
      enabled: true
    health: 
      enabled: true
    info:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
  data:
    mongodb:
      uri: mongodb://hakuUser:hakuPass@localhost:27017/haku_db
      database: haku_db
      port: 27017
      host: localhost
      username: hakuUser
      password: hakuPass
  cloud:
    discovery:
      client:
        health-indicator:
          enabled: true
